import subprocess
from pathlib import Path
from typing import List

import pytest


@pytest.fixture(autouse=True)
def _isolate_dotenv(monkeypatch):
    """Tests must never read the developer's real .env file.

    load_dotenv() locates .env relative to the calling module's directory, so
    it finds the project .env even when a test monkeypatch.delenv()s a key or
    chdirs away — making 'missing key' tests pass or fail depending on the
    developer's local setup. No-op it for every test; tests that need env
    values set them explicitly with monkeypatch.setenv().
    """
    monkeypatch.setattr("splurj_engine.load_dotenv", lambda *args, **kwargs: False)
    monkeypatch.setattr("generate_character_reference.load_dotenv", lambda *args, **kwargs: False)


def _run(cmd):
    result = subprocess.run(cmd, capture_output=True, text=True)
    assert result.returncode == 0, result.stderr


@pytest.fixture
def fixture_image(tmp_path) -> Path:
    """A tiny real 64x64 blue PNG, generated by ffmpeg's lavfi test source."""
    path = tmp_path / "fixture_image.png"
    _run(["ffmpeg", "-y", "-f", "lavfi", "-i", "color=c=blue:s=64x64", "-frames:v", "1", str(path)])
    return path


@pytest.fixture
def fixture_audio(tmp_path) -> Path:
    """A tiny real 8-second silent MP3, generated by ffmpeg's lavfi test source.

    8s (not 1s) so tests exercising a multi-pose crossfade segment can request
    a duration long enough to avoid pose-count thinning; every existing caller
    passes an explicit `duration` to create_segment_video anyway, which is what
    actually trims the output via ffmpeg's `-t`, so this has no effect on them.
    """
    path = tmp_path / "fixture_audio.mp3"
    _run(["ffmpeg", "-y", "-f", "lavfi", "-i", "anullsrc=r=44100:cl=mono", "-t", "8", str(path)])
    return path


@pytest.fixture
def fixture_images(tmp_path) -> List[Path]:
    """3 tiny real 64x64 PNGs in distinct colors, generated by ffmpeg's lavfi
    test source -- used to prove crossfading actually changes frame content
    across a multi-pose segment clip, not just that the resolution is right."""
    colors = ["blue", "red", "green"]
    paths = []
    for i, color in enumerate(colors):
        path = tmp_path / f"fixture_image_{i}.png"
        _run(["ffmpeg", "-y", "-f", "lavfi", "-i", f"color=c={color}:s=64x64", "-frames:v", "1", str(path)])
        paths.append(path)
    return paths
